"use strict";

const tg = window.Telegram?.WebApp || null;
try { tg?.ready?.(); tg?.expand?.(); tg?.setHeaderColor?.("#070712"); tg?.setBackgroundColor?.("#070712"); } catch (_) {}
const user = tg?.initDataUnsafe?.user || null;
// Kept exactly as a frontend read-only source. No backend endpoint is changed.
const API_URL = "https://galaxylab.i234.me:8443/api/files";
const AI = { together:{models:[["meta-llama/Llama-3.3-70B-Instruct-Turbo","Llama 3.3 70B"],["meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo","Llama 3.1 8B"],["Qwen/Qwen2.5-72B-Instruct-Turbo","Qwen 2.5 72B"]]}, openai:{models:[["gpt-4o-mini","GPT-4o mini"],["gpt-4.1-mini","GPT-4.1 mini"]]}, anthropic:{models:[["claude-3-5-haiku-latest","Claude 3.5 Haiku"]]}, google:{models:[["gemini-2.0-flash","Gemini 2.0 Flash"]]} };
const initialDB = { notes:[], journal:[], telegramTexts:{}, stats:{streak:0,lastLogin:null,wordsWritten:0}, settings:{aiProvider:"together",aiModel:"meta-llama/Llama-3.3-70B-Instruct-Turbo",apiKeys:{},togetherApiKey:""} };
const folders = [{id:"smart_notes",name:"Smart notes",icon:"notes",types:["smart_note"]},{id:"telegram_texts",name:"Telegram text",icon:"text",types:["text"]},{id:"documents",name:"Documents",icon:"docs",types:["document","audio","voice"]},{id:"media",name:"Media",icon:"media",types:["photo","video","animation","video_note"]}];
let db = loadDB(), files = [], activeFolder = null, searchQuery = "", mood = "calm", insightPeriod = "day", brainGraph = null, calendarDate = new Date(), hoveredBrainNode = null;
const clone = value => JSON.parse(JSON.stringify(value));
const esc = (value = "") => String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const clean = (value = "") => String(value).replace(/\s+/g," ").trim();
const words = (value = "") => clean(value).toLowerCase().replace(/[^\p{L}\p{N}\s-]/gu," ").split(/\s+/).filter(word => word.length > 1);
function safeUrl(value){ try { const url = new URL(value,location.href); return ["http:","https:"].includes(url.protocol) ? url.href : ""; } catch (_) { return ""; } }
function dateKey(value){ const date = new Date(value); return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`; }
function formatDate(value, options={day:"numeric",month:"long",year:"numeric"}){ return new Intl.DateTimeFormat("en-US",options).format(new Date(value)); }
function loadDB(){ try { const saved = JSON.parse(localStorage.getItem("infinityLocalDB")); const result = {...clone(initialDB),...(saved||{}),stats:{...initialDB.stats,...(saved?.stats||{})},settings:{...initialDB.settings,...(saved?.settings||{})}}; result.notes = Array.isArray(result.notes)?result.notes:[]; result.journal = Array.isArray(result.journal)?result.journal:[]; result.telegramTexts ||= {}; result.settings.apiKeys ||= {}; if(result.settings.togetherApiKey&&!result.settings.apiKeys.together) result.settings.apiKeys.together=result.settings.togetherApiKey; return result; } catch (_) { return clone(initialDB); } }
function saveDB(){ localStorage.setItem("infinityLocalDB",JSON.stringify(db)); updateStats(); updateStorage(); }
function allItems(){ return [...files,...db.notes.map(note=>({internalId:`note_${note.id}`,id:note.id,type:"smart_note",title:note.title||"Untitled note",text:note.text||"",tags:note.tags||[],date:note.date,size:new Blob([note.text||""]).size}))]; }
function fileSize(file){ return Number([file.size,file.file_size,file.fileSize,file.bytes,file.content_length,file.contentLength,file.document?.file_size,file.photo?.file_size,file.video?.file_size,file.audio?.file_size].find(value=>Number(value)>0)||0); }
function fmtSize(size){ if(size<1024)return `${size} B`; if(size<1024**2)return `${(size/1024).toFixed(1)} KB`; if(size<1024**3)return `${(size/1024**2).toFixed(1)} MB`; return `${(size/1024**3).toFixed(2)} GB`; }
function updateStorage(){ const total=allItems().reduce((sum,file)=>sum+fileSize(file),0), visual=total?Math.min(8+Math.log10(total+1)*11,96):0; document.getElementById("dataUsedText").textContent=fmtSize(total); document.getElementById("dataUsedFill").style.width=`${visual}%`; document.getElementById("storageRangeDot").style.left=`${visual}%`; }
function updateStats(){ document.getElementById("streakCounter").textContent=db.stats.streak||0; document.getElementById("wordsCount").textContent=db.stats.wordsWritten||0; document.getElementById("totalFilesCount").textContent=allItems().length; }
function updateStreak(){ const today=new Date().toDateString(); if(db.stats.lastLogin===today)return; db.stats.streak=db.stats.lastLogin===new Date(Date.now()-86400000).toDateString()?Number(db.stats.streak||0)+1:1; db.stats.lastLogin=today; saveDB(); }
function showStreak(){ const days=Number(db.stats.streak||0), next=Math.max(0,7-(days%7)); toast(`Current streak: ${days} ${days===1?"day":"days"}. You are active today${next?`. ${next} more day${next===1?"":"s"} to your next 7-day milestone.`:" — a perfect 7-day milestone!"}`); }
function provider(){ return AI[db.settings.aiProvider]?db.settings.aiProvider:"together"; } function model(){const models=AI[provider()].models;return models.some(([name])=>name===db.settings.aiModel)?db.settings.aiModel:models[0][0];} function key(){const p=provider();return (db.settings.apiKeys?.[p]||(p==="together"?db.settings.togetherApiKey:"")||"").trim();}
function renderModels(name,selected=""){const select=document.getElementById("aiModel"),models=AI[name].models;select.innerHTML=models.map(([value,label])=>`<option value="${esc(value)}">${esc(label)}</option>`).join("");const result=models.some(([value])=>value===selected)?selected:models[0][0];select.value=result;return result;}
function loadSettings(){const current=provider();document.getElementById("aiProvider").value=current;db.settings.aiModel=renderModels(current,db.settings.aiModel);document.getElementById("togetherApiKey").value=db.settings.apiKeys?.[current]||"";}
function changeProvider(){const old=provider(),next=document.getElementById("aiProvider").value;db.settings.apiKeys[old]=document.getElementById("togetherApiKey").value.trim();db.settings.aiProvider=next;db.settings.aiModel=renderModels(next);document.getElementById("togetherApiKey").value=db.settings.apiKeys[next]||"";}
function saveSettings(){const current=document.getElementById("aiProvider").value;db.settings.aiProvider=current;db.settings.aiModel=document.getElementById("aiModel").value;db.settings.apiKeys[current]=document.getElementById("togetherApiKey").value.trim();db.settings.togetherApiKey=db.settings.apiKeys.together||"";saveDB();toast("AI settings saved");}
async function ai(system,prompt,limit=550){if(!key()){toast("Add an API key in AI settings first");return null;}try{let response,text="";if(["together","openai"].includes(provider())){response=await fetch(provider()==="together"?"https://api.together.xyz/v1/chat/completions":"https://api.openai.com/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key()}`,"Content-Type":"application/json"},body:JSON.stringify({model:model(),temperature:.35,max_tokens:limit,messages:[{role:"system",content:system},{role:"user",content:prompt}]})});if(!response.ok)throw Error();text=(await response.json()).choices?.[0]?.message?.content||"";}if(provider()==="anthropic"){response=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"x-api-key":key(),"anthropic-version":"2023-06-01","Content-Type":"application/json"},body:JSON.stringify({model:model(),max_tokens:limit,system,messages:[{role:"user",content:prompt}]})});if(!response.ok)throw Error();text=(await response.json()).content?.[0]?.text||"";}if(provider()==="google"){response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model())}:generateContent?key=${encodeURIComponent(key())}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({system_instruction:{parts:[{text:system}]},contents:[{role:"user",parts:[{text:prompt}]}]})});if(!response.ok)throw Error();text=(await response.json()).candidates?.[0]?.content?.parts?.[0]?.text||"";}return text.trim()||null;}catch(_){toast("Infinity AI could not return a response");return null;}}
function isTextFile(file){const name=`${file.name||""} ${file.file_name||""} ${file.title||""}`.toLowerCase(),mime=String(file.mime_type||file.mime||file.content_type||"").toLowerCase();return file.type==="text"||mime.startsWith("text/")||/\.(txt|md|csv|json|log|html|css|js|xml)$/i.test(name);}
async function readTelegramText(file){const id=file.id||file.internalId;if(file.text)return file.text;if(db.telegramTexts[id])return db.telegramTexts[id];const url=safeUrl(file.url);if(!url||!isTextFile(file))return "";try{const response=await fetch(url);if(!response.ok)return "";const text=(await response.text()).slice(0,100000);db.telegramTexts[id]=text;saveDB();return text;}catch(_){return "";}}
async function loadFiles(){try{const response=await fetch(`${API_URL}?user_id=${encodeURIComponent(user?.id||"browser-user")}&limit=100`);if(!response.ok)throw Error();const data=await response.json();files=await Promise.all((data.files||[]).map(async(file,index)=>{const item={...file,internalId:`server_${file.id||index}`,id:file.id||`server_${index}`,type:file.type||file.file_type||"document",title:file.title||file.name||file.file_name||"File",text:file.text||file.caption||"",url:file.url||file.file_url||"",size:fileSize(file)};if(isTextFile(item)){item.type="text";item.text=await readTelegramText(item);}return item;}));}catch(_){files=[];}updateStorage();updateStats();renderFiles();}
function noteCounter(){const input=document.getElementById("smartNoteInput");document.getElementById("noteCharCounter").textContent=`${input.value.length} / ${input.maxLength}`;}
async function saveSmartNote(){const input=document.getElementById("smartNoteInput"),text=input.value.trim();if(!text)return toast("Write a thought first");input.value="";noteCounter();let title=text.slice(0,60),tags=[];if(key()){const result=await ai('Return only JSON: {"title":"short English title","tags":["tag"]}. Up to 5 concise tags.',text,180);try{const parsed=JSON.parse(result?.match(/\{[\s\S]*\}/)?.[0]||"{}");title=String(parsed.title||title).slice(0,90);tags=Array.isArray(parsed.tags)?parsed.tags.slice(0,5).map(String):[];}catch(_){}}db.notes.unshift({id:Date.now(),title,text,tags,date:new Date().toISOString()});db.stats.wordsWritten+=words(text).length;saveDB();renderFiles();toast("Thought saved to Infinity");}
function setMood(value){mood=value;document.querySelectorAll("[data-mood]").forEach(button=>button.classList.toggle("selected",button.dataset.mood===value));}
function saveJournal(){const input=document.getElementById("journalInput"),text=input.value.trim();if(!text)return toast("Write an entry first");db.journal.unshift({id:Date.now(),text,mood,date:new Date().toISOString()});db.stats.wordsWritten+=words(text).length;input.value="";saveDB();renderActivity();toast("Journal entry saved");}
function fileIcon(type){const common='<svg viewBox="0 0 24 24" aria-hidden="true">';const icons={notes:`${common}<path d="M12 3 14 9l6 3-6 3-2 6-2-6-6-3 6-3 2-6Z"/></svg>`,text:`${common}<path d="M6 3h9l3 3v15H6z"/><path d="M9 10h6m-6 4h6m-6 4h4"/></svg>`,docs:`${common}<path d="M6 3h9l3 3v15H6z"/><path d="M15 3v4h4M9 12h6m-6 4h6"/></svg>`,media:`${common}<rect x="3" y="5" width="18" height="14" rx="2"/><circle cx="8" cy="10" r="1.5"/><path d="m5 17 5-5 3 3 2-2 4 4"/></svg>`};const icon=type==="smart_note"?"notes":type==="text"?"text":["photo","video","animation","video_note"].includes(type)?"media":"docs";return `<span class="file-icon icon-${icon}">${icons[icon]}</span>`;}
function renderFiles(){const grid=document.getElementById("folderGridView"),content=document.getElementById("folderContentsView"),heading=document.getElementById("filesHeading");if(!activeFolder){grid.hidden=false;content.hidden=true;heading.textContent="Files";document.getElementById("folderGrid").innerHTML=folders.map(folder=>{const count=allItems().filter(item=>folder.types.includes(item.type)).length;return `<button class="folder-card" type="button" onclick="openFolder('${folder.id}')"><span class="file-icon icon-${folder.icon}">${fileIcon(folder.icon==="notes"?"smart_note":folder.icon==="text"?"text":folder.icon==="media"?"photo":"document").replace(/^.*?>([\s\S]*)<\/span>$/,"$1")}</span><span class="folder-name">${esc(folder.name)}</span><span class="folder-count">${count} item${count===1?"":"s"}</span></button>`;}).join("");return;}grid.hidden=true;content.hidden=false;const folder=folders.find(item=>item.id===activeFolder);heading.textContent=folder.name;const items=allItems().filter(item=>folder.types.includes(item.type)&&(!searchQuery||`${item.title} ${item.text} ${(item.tags||[]).join(" ")}`.toLowerCase().includes(searchQuery)));const list=document.getElementById("folderGallery");if(!items.length){list.innerHTML='<div class="empty-state">Nothing here yet.</div>';return;}list.innerHTML="";items.forEach(item=>{const card=document.createElement("button");card.type="button";card.className="file-card";const image=item.type==="photo"&&safeUrl(item.url)?`<img src="${safeUrl(item.url)}" alt="${esc(item.title)}">`:fileIcon(item.type);card.innerHTML=`${image}<span><strong>${esc(item.title)}</strong><p>${esc(clean(item.text).slice(0,150)||"No preview available")}</p></span>`;card.onclick=()=>item.type==="photo"&&safeUrl(item.url)?openMedia(item):openDetails(item);list.appendChild(card);});}
function openFolder(id){activeFolder=id;searchQuery="";document.getElementById("searchInput").value="";renderFiles();}function closeFolder(){activeFolder=null;renderFiles();}function handleSearch(){searchQuery=document.getElementById("searchInput").value.trim().toLowerCase();if(activeFolder)renderFiles();}
function relevant(question){const query=words(question);return db.notes.map(note=>({...note,score:query.reduce((score,word)=>score+(words(`${note.title} ${note.text} ${(note.tags||[]).join(" ")}`).includes(word)?1:0),0)})).sort((a,b)=>b.score-a.score).slice(0,5);}
function chatMessage(text,role,sources=[]){const box=document.getElementById("chatContainer"),item=document.createElement("div");item.className=`chat-msg ${role}`;if(role==="ai")item.innerHTML='<span class="message-label">INFINITY AI</span>';item.append(document.createTextNode(text));if(sources.length){const sourceBox=document.createElement("div");sourceBox.className="chat-sources";sources.forEach(source=>{const button=document.createElement("button");button.className="chat-source";button.textContent=source.title;button.onclick=()=>openDetails(source);sourceBox.appendChild(button);});item.appendChild(sourceBox);}box.appendChild(item);box.scrollTop=box.scrollHeight;return item;}
function askSuggestion(text){document.getElementById("chatInput").value=text;sendChatMessage();}
async function sendChatMessage(){const input=document.getElementById("chatInput"),question=input.value.trim();if(!question)return;input.value="";chatMessage(question,"user");const notes=relevant(question);if(!notes.length)return chatMessage("I could not find a relevant saved note yet. Add a thought first, then ask me again.","ai");const context=notes.map((note,index)=>`[${index+1}] ${note.title}\n${note.text.slice(0,1000)}`).join("\n\n"),loading=chatMessage("Thinking…","ai"),answer=await ai("Answer only from the supplied context. Be concise, helpful, and answer in English. If the context does not contain the answer, say so.",`${context}\n\nQUESTION:\n${question}`,420);loading.remove();chatMessage(answer||"I could not complete that response.","ai",notes);}
function handleChatKey(event){if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();sendChatMessage();}}
function noteLinks(notes){const degree={},result=[];notes.forEach((a,index)=>notes.slice(index+1).forEach(b=>{const tags=new Set((a.tags||[]).map(tag=>tag.toLowerCase())),common=(b.tags||[]).filter(tag=>tags.has(tag.toLowerCase()));if(common.length)result.push({source:`note_${a.id}`,target:`note_${b.id}`,strength:common.length});}));return result.sort((a,b)=>b.strength-a.strength).filter(link=>{if((degree[link.source]||0)>=3||(degree[link.target]||0)>=3)return false;degree[link.source]=(degree[link.source]||0)+1;degree[link.target]=(degree[link.target]||0)+1;return true;});}
function updateBrainZoomInfo(){if(!brainGraph)return;const pos=brainGraph.cameraPosition(),info=document.getElementById("brainZoomInfo"),close=pos.z<460;info.hidden=!close;if(close){const node=hoveredBrainNode;info.innerHTML=node?`<strong>${esc(node.name)}</strong>${esc(node.description)}`:"Labels are now visible — hover or tap a sphere to explore it.";}}
function openBrainMap(){const modal=document.getElementById("brainMapModal"),mount=document.getElementById("3d-graph");modal.classList.add("active");mount.innerHTML="";document.getElementById("brainZoomInfo").hidden=true;if(!db.notes.length||typeof window.ForceGraph3D!=="function"){mount.innerHTML='<p class="brain-empty">Add a few tagged notes to start your neural map.</p>';return;}const nodes=db.notes.map((note,index)=>({id:`note_${note.id}`,note,name:note.title,description:clean(note.text).slice(0,160),color:["#84a7ff","#a77cff","#75edc5","#ffbf63"][index%4],val:3+Math.min((note.tags||[]).length,5)}));brainGraph=window.ForceGraph3D()(mount).graphData({nodes,links:noteLinks(db.notes)}).backgroundColor("#05050d").nodeVal("val").nodeColor("color").nodeLabel(node=>`<b>${esc(node.name)}</b><br>${esc(node.description)}`).linkColor(link=>link.strength>1?"rgba(167,124,255,.72)":"rgba(132,167,255,.42)").linkWidth(link=>.8+link.strength*.6).linkDirectionalParticles(1).linkDirectionalParticleWidth(1.4).onNodeClick(node=>openDetails(node.note)).onNodeHover(node=>{hoveredBrainNode=node;mount.style.cursor=node?"pointer":"grab";updateBrainZoomInfo();});brainGraph.controls().enableDamping=true;brainGraph.controls().dampingFactor=.1;brainGraph.controls().addEventListener("change",updateBrainZoomInfo);brainGraph.d3Force("charge")?.strength(-125);brainGraph.d3Force("link")?.distance(100);document.getElementById("brainSearchInput").oninput=event=>{const found=nodes.find(node=>node.name.toLowerCase().includes(event.target.value.trim().toLowerCase()));if(found)brainGraph.cameraPosition({x:found.x+50,y:found.y+50,z:found.z+110},found,600);};setTimeout(()=>brainGraph?.zoomToFit(650,70),200);}
function toggleBrainHelp(){const help=document.getElementById("brainHelp");help.hidden=!help.hidden;}function closeBrainMap(){brainGraph?.controls()?.removeEventListener?.("change",updateBrainZoomInfo);brainGraph?._destructor?.();brainGraph=null;hoveredBrainNode=null;document.getElementById("brainMapModal").classList.remove("active");}
function openDetails(item){document.querySelector(".details-overlay")?.remove();const overlay=document.createElement("div");overlay.className="details-overlay";overlay.innerHTML=`<section class="details-card" role="dialog" aria-modal="true"><button class="sheet-close" type="button" aria-label="Close"><svg viewBox="0 0 24 24"><path d="m18 6-12 12M6 6l12 12"/></svg></button><div class="details-date">${esc(formatDate(item.date||Date.now(),{day:"numeric",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"}))}</div><h2>${esc(item.title||"Journal entry")}</h2><div class="details-text">${esc(item.text||"No content was provided.").replaceAll("\n","<br>")}</div></section>`;overlay.onclick=event=>{if(event.target===overlay||event.target.closest(".sheet-close"))overlay.remove();};document.body.appendChild(overlay);}
function openMedia(file){const url=safeUrl(file.url);if(!url)return;document.getElementById("modalContent").innerHTML=`<img src="${url}" alt="${esc(file.title)}">`;document.getElementById("mediaModal").classList.add("active");}function closeModal(){document.getElementById("mediaModal").classList.remove("active");document.getElementById("modalContent").innerHTML="";}
function openJournalCalendar(){calendarDate=new Date();renderJournalCalendar();}
function changeCalendarMonth(delta){calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+delta,1);renderJournalCalendar();}
function renderJournalCalendar(){document.querySelector(".calendar-overlay")?.remove();const date=new Date(calendarDate.getFullYear(),calendarDate.getMonth(),1),year=date.getFullYear(),month=date.getMonth(),entriesByDay=new Map();db.journal.forEach(entry=>{const key=dateKey(entry.date);if(!entriesByDay.has(key))entriesByDay.set(key,[]);entriesByDay.get(key).push(entry);});const first=(date.getDay()+6)%7,count=new Date(year,month+1,0).getDate(),todayKey=dateKey(new Date());let cells='<span class="calendar-day empty"></span>'.repeat(first);for(let day=1;day<=count;day++){const key=`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`,has=entriesByDay.has(key);cells+=`<button class="calendar-day ${has?"has-entry":""} ${key===todayKey?"today":""}" ${has?`onclick="openEntriesForDay('${key}')"`:""} type="button">${day}</button>`;}const overlay=document.createElement("div");overlay.className="calendar-overlay";overlay.innerHTML=`<section class="calendar-card" role="dialog" aria-modal="true"><button class="sheet-close" type="button" aria-label="Close"><svg viewBox="0 0 24 24"><path d="m18 6-12 12M6 6l12 12"/></svg></button><div class="calendar-nav"><button type="button" onclick="changeCalendarMonth(-1)" aria-label="Previous month"><svg viewBox="0 0 24 24"><path d="m15 18-6-6 6-6"/></svg></button><h2>${esc(formatDate(date,{month:"long",year:"numeric"}))}</h2><button type="button" onclick="changeCalendarMonth(1)" aria-label="Next month"><svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg></button></div><div class="weekdays"><span>Mo</span><span>Tu</span><span>We</span><span>Th</span><span>Fr</span><span>Sa</span><span>Su</span></div><div class="calendar-grid">${cells}</div></section>`;overlay.onclick=event=>{if(event.target===overlay||event.target.closest(".sheet-close"))overlay.remove();};document.body.appendChild(overlay);}
function openEntriesForDay(key){const entries=db.journal.filter(entry=>dateKey(entry.date)===key).sort((a,b)=>new Date(b.date)-new Date(a.date));document.querySelector(".calendar-overlay")?.remove();const overlay=document.createElement("div");overlay.className="details-overlay";overlay.innerHTML=`<section class="details-card" role="dialog" aria-modal="true"><button class="sheet-close" type="button" aria-label="Close"><svg viewBox="0 0 24 24"><path d="m18 6-12 12M6 6l12 12"/></svg></button><div class="details-date">${esc(formatDate(`${key}T12:00:00`,{weekday:"long",day:"numeric",month:"long",year:"numeric"}))}</div><h2>${entries.length} journal ${entries.length===1?"entry":"entries"}</h2>${entries.map(entry=>`<article class="details-text" style="margin-top:16px;padding-top:16px;border-top:1px solid var(--line)">${esc(entry.text).replaceAll("\n","<br>")}</article>`).join("")}</section>`;overlay.onclick=event=>{if(event.target===overlay||event.target.closest(".sheet-close"))overlay.remove();};document.body.appendChild(overlay);}
function renderActivity(){const today=new Date(),days=Array.from({length:7},(_,index)=>{const date=new Date(today);date.setDate(today.getDate()-(6-index));const key=dateKey(date);return{label:formatDate(date,{weekday:"short"}).slice(0,2),count:db.notes.filter(item=>dateKey(item.date)===key).length+db.journal.filter(item=>dateKey(item.date)===key).length};}),max=Math.max(1,...days.map(day=>day.count));document.getElementById("activityTotal").textContent=days.reduce((sum,day)=>sum+day.count,0);document.getElementById("activityChart").innerHTML=days.map(day=>`<div class="activity-bar-wrap"><div class="activity-bar" style="height:${Math.max(8,day.count/max*100)}%"></div><span class="activity-label">${day.label}</span></div>`).join("");}
async function generateDailyInsight(){const end=new Date(),start=new Date();if(insightPeriod==="week")start.setDate(end.getDate()-6);const records=[...db.notes,...db.journal].filter(item=>new Date(item.date)>=start).sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,8).map(item=>`${item.title||"Journal"}: ${String(item.text).slice(0,550)}`).join("\n---\n"),area=document.getElementById("dailyInsightContent");if(!records){area.textContent="There are no saved entries in this period.";return;}area.textContent="Creating your reflection…";const result=await ai("Create a kind, concise personal reflection using only these entries. Mention possible feelings, themes, and one gentle practical suggestion. Do not diagnose. Answer in English in up to 5 sentences.",records,260);area.textContent=result||"Infinity AI could not create a reflection.";}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="infinity-backup.json";link.click();URL.revokeObjectURL(url);}function importData(event){const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{localStorage.setItem("infinityLocalDB",String(reader.result));location.reload();}catch(_){toast("Import failed");}};reader.readAsText(file);}
function switchTab(id,button){document.querySelectorAll(".tab").forEach(item=>item.classList.remove("active"));document.getElementById(`tab-${id}`).classList.add("active");document.querySelectorAll(".nav-item").forEach(item=>item.classList.remove("active"));button.classList.add("active");if(id==="profile")renderActivity();try{tg?.HapticFeedback?.selectionChanged?.();}catch(_){}}
function toast(text){const item=document.createElement("div");item.className="toast";item.textContent=text;document.getElementById("toast-box").appendChild(item);setTimeout(()=>item.remove(),3600);}
async function init(){const name=user?.first_name||"User";document.getElementById("userName").textContent=name;document.getElementById("userAvatar").textContent=name[0].toUpperCase();document.getElementById("journalToday").textContent=formatDate(new Date(),{weekday:"long",month:"long",day:"numeric"});document.getElementById("smartNoteInput").oninput=noteCounter;document.getElementById("aiProvider").onchange=changeProvider;document.getElementById("saveSettingsBtn").onclick=saveSettings;document.getElementById("toggleApiKey").onclick=()=>{const input=document.getElementById("togetherApiKey");input.type=input.type==="password"?"text":"password";};document.getElementById("toggleAISettings").onclick=()=>{const panel=document.getElementById("aiSettingsPanel"),toggle=document.getElementById("toggleAISettings");panel.hidden=!panel.hidden;toggle.setAttribute("aria-expanded",String(!panel.hidden));};document.querySelectorAll("[data-insight-period]").forEach(button=>button.onclick=()=>{insightPeriod=button.dataset.insightPeriod;document.querySelectorAll("[data-insight-period]").forEach(item=>item.classList.toggle("active",item===button));});loadSettings();noteCounter();updateStreak();setMood("calm");await loadFiles();renderActivity();setTimeout(()=>document.getElementById("app-loader").classList.add("hidden"),250);}
document.addEventListener("DOMContentLoaded",init);
